### ISSUE TITLE
No video captured

### ISSUE THREAD

**Issue by darrinps** [tiomamaster/WatermarkableCamera#1]
Build and run, and always get a 3 second long image on the screen with music playing in the background. It does not capture the actual video.

**Comment by tiomamaster** [comment]
I tested on Huawei Honor 6 and OnePlus 7t and video is actually captured and stored here /storage/emulated/0/Android/data/com.gmail.tiomamaster.watermarkablecamera/files

**Comment by darrinps** [comment]
I see a "TODO" in your manifest that kind of explains why I didn't see it.

Since Android 10, the way you have to handle saving things has changed. I was expecting it to go into the Gallery with all other videos. Anyway, I added some code to share the video and do see that it works. Thanks!
