### ISSUE TITLE
Can pause preview, but cannot end preview.

### ISSUE THREAD

**Issue by darrinps** [tiomamaster/WatermarkableCamera#2]
Have this code working (works well) but in most camera apps there is a way to stop the preview and just show an alternate view over the area where the camera view will go, then start the preview, then hit record.

I was able to get your code to start without going directly into preview mode, but I cannot find a way to go back to the original state, which is the one without an image from the camera showing on the screen.

What I have tried is this:

`  
   private val cameraStateCallback = object : CameraDevice.StateCallback() {
   override fun onOpened(camera: CameraDevice) {
   cameraOpenCloseLock.release()
   cameraDevice = camera
   //startPreview() //I commented out this line
   }

   private fun beginStopPreview() {
     if(btnStartStopCamera.text.startsWith("Start")) {
     btnStartStopCamera.text = "Stop Preview"
     startPreview()
   } else {
     btnStartStopCamera.text = "Start Preview"
     closePreviewSession()
   }
   }
`

With this in place, the app will start without the preview from the camera and just shows the two buttons you had and a third one I added to start/stop preview. This is exactly what is wanted. 

When you hit Start Preview, it works as expected and the preview from the camera is shown on screen with the buttons still showing over top. 

When you hit Stop Preview though, instead of it going back to the original view that shows just the buttons and no preview, you get a freeze frame of what the camera last saw.

I'd like to have the stopped preview experience be the same as before the preview was first started.

Is there a way to do this please?

**Comment by tiomamaster** [comment]
Yes, you can clear open gl display in Renderer.onDrawFrame when camera preview is stopped. See https://stackoverflow.com/questions/15007129/clearing-an-opengl-display-in-android

**Comment by darrinps** [comment]
I'll give that a try then. Thanks!

**Comment by darrinps** [comment]
Not too sure based on the example how to do this.

Are you saying that your Renderer's onDrawFrame() should be changed?

Or saying that a new function should be created something like this?

public void clearBuffers(boolean color, boolean depth, boolean stencil) {
    int bits = 0;
    if (color) {
        bits = GLES20.GL_COLOR_BUFFER_BIT;
    }
    if (depth) {
        bits |= GLES20.GL_DEPTH_BUFFER_BIT;
    }
    if (stencil) {
        bits |= GLES20.GL_STENCIL_BUFFER_BIT;
    }
    if (bits != 0) {
        GLES20.glClear(bits);
    }
}

Then in closePreviewSession call renderer.clearBuffers(true, true, true)

**Comment by tiomamaster** [comment]
You should clear opengl display in onDrawFrame when camera preview is stopped.

**Comment by darrinps** [comment]
That works well!

In case someone else wants to do this, what I did was...

In your Renderer class I added:

` 

    private var isPreviewActive = true
    fun setPreviewActive(active : Boolean) {
        isPreviewActive = active
    }`

and modified onDrawFrame like this:

`

      if(!isPreviewActive) {
            var bits = gl2.GL_COLOR_BUFFER_BIT
            bits = bits or gl2.GL_DEPTH_BUFFER_BIT
            bits = bits or gl2.GL_STENCIL_BUFFER_BIT
            gl2.glClear(bits)
        }`

Then in CameraActivity startPreview() I call renderer.setPreviewActive(true), and in closePreviewSession I call renderer.setPreviewActive(false).
